name: Netagame Laevo Casino Portal
description: |
  Current Netagame Gaming portal stack, uses mounted files.
  Includes a Redis container for sessions. As well as filepermissions and nginx cache util containers.

version: 1.2
category: Web
maintainer: mgm@netagame.com
license: Proprietary
projectURL: http://www.netagame.com
