name: Wordpress
description: bSocial Base Wordpress
version: 2.2
category: Web
maintainer: mgm@bsocial.io
license: Proprietary
projectURL: http://www.bsocial.io
description: Optimized NGINX based Wordpress Template, using mounted files and memcached.